#pragma once 


//THIS IS THE HEADER TO MANAGE EVERYTHING RELATED WITH THE
//SERIAL COMMUNICATION PC <---> ESP32

//THIS FILE WILL ALSO INCLUDE THE FUNCTIONS INTENDER FOR TESTS IN THE DEVELOPER MODES


void serial_init();//default is 115200

